const studentData =
[
    {
        "id": 1,
        "name":"OMAR CALEB CORPUS MENDOZA",
        "group": '6E',
        "probdes": 20,
        "sex": "F",
		"age": "18",
        "address": "U",
        "famsize":"GT3",
        "Pstatus":"A",
        "Medu":"4",
        "Fedu":"4",
        "reason":"course",
        "guardian":"mother",
        "traveltime":"2",
        "studytime":"2",
        "failures":"0",
        "schoolsup":"yes",
        "famsup":"no",
        "paid":"no",
        "activities":"no",
        "higher":"yes",
        "internet":"yes",
        "romantic":"no",
        "famrel":"4",
        "freetime":"3",
        "goout":"3",
        "Dalc":"1",
        "Walc":"1",
        "health":"3",
        "absences":"6",
        "G1":"9",
        "G2":"8",
        "G3":"7"
    },
    {
        "id": 2,
        "name":"Superman",
        "group": '4A',
        "probdes": 30,
        "sex": "M",
		"age": "18",
        "address": "U",
        "famsize":"GT3",
        "Pstatus":"A",
        "Medu":"4",
        "Fedu":"4",
        "reason":"course",
        "guardian":"mother",
        "traveltime":"2",
        "studytime":"2",
        "failures":"0",
        "schoolsup":"yes",
        "famsup":"no",
        "paid":"no",
        "activities":"no",
        "higher":"yes",
        "internet":"yes",
        "romantic":"no",
        "famrel":"4",
        "freetime":"3",
        "goout":"3",
        "Dalc":"1",
        "Walc":"1",
        "health":"3",
        "absences":"6",
        "G1":"7",
        "G2":"8",
        "G3":"8"
    },
    {
        "id": 3,
        "name":"Linterna Verde",
        "group": '3J',
        "probdes": 70,
        "sex": "F",
		"age": "18",
        "address": "U",
        "famsize":"LE3",
        "Pstatus":"A",
        "Medu":"4",
        "Fedu":"4",
        "reason":"other",
        "guardian":"mother",
        "traveltime":"2",
        "studytime":"2",
        "failures":"0",
        "schoolsup":"yes",
        "famsup":"no",
        "paid":"no",
        "activities":"no",
        "higher":"yes",
        "internet":"yes",
        "romantic":"no",
        "famrel":"4",
        "freetime":"3",
        "goout":"3",
        "Dalc":"1",
        "Walc":"1",
        "health":"3",
        "absences":"6",
        "G1":"7",
        "G2":"5",
        "G3":"7"
    },
    {
        "id": 4,
        "name":"Mujer Maravilla",
        "group": '6B',
        "probdes": 3,
        "sex": "F",
		"age": "18",
        "address": "U",
        "famsize":"GT3",
        "Pstatus":"A",
        "Medu":"4",
        "Fedu":"4",
        "reason":"course",
        "guardian":"mother",
        "traveltime":"2",
        "studytime":"2",
        "failures":"0",
        "schoolsup":"yes",
        "famsup":"no",
        "paid":"no",
        "activities":"no",
        "higher":"yes",
        "internet":"yes",
        "romantic":"no",
        "famrel":"4",
        "freetime":"3",
        "goout":"3",
        "Dalc":"1",
        "Walc":"1",
        "health":"3",
        "absences":"6",
        "G1":"8",
        "G2":"9",
        "G3":"10"
    },
    {
        "id": 5,
        "name":"Flash",
        "group": '1A',
        "probdes": 58,
        "sex": "F",
		"age": "18",
        "address": "U",
        "famsize":"GT3",
        "Pstatus":"A",
        "Medu":"4",
        "Fedu":"4",
        "reason":"course",
        "guardian":"mother",
        "traveltime":"2",
        "studytime":"2",
        "failures":"0",
        "schoolsup":"yes",
        "famsup":"no",
        "paid":"no",
        "activities":"no",
        "higher":"yes",
        "internet":"yes",
        "romantic":"no",
        "famrel":"4",
        "freetime":"3",
        "goout":"3",
        "Dalc":"1",
        "Walc":"1",
        "health":"3",
        "absences":"6",
        "G1":"10",
        "G2":"9",
        "G3":"8"
    },
     {
        "id": 6,
        "name":"Aquaman",
        "group": '1B',
        "probdes": 13,
        "sex": "F",
		"age": "18",
        "address": "U",
        "famsize":"GT3",
        "Pstatus":"A",
        "Medu":"4",
        "Fedu":"4",
        "reason":"course",
        "guardian":"mother",
        "traveltime":"2",
        "studytime":"2",
        "failures":"0",
        "schoolsup":"yes",
        "famsup":"no",
        "paid":"no",
        "activities":"no",
        "higher":"yes",
        "internet":"yes",
        "romantic":"no",
        "famrel":"4",
        "freetime":"3",
        "goout":"3",
        "Dalc":"1",
        "Walc":"1",
        "health":"3",
        "absences":"6",
        "G1":"10",
        "G2":"9",
        "G3":"9"
    },
    {
        "id": 7,
        "name":"Robin",
        "group": '6B',
        "probdes": 84,
        "sex": "F",
		"age": "18",
        "address": "U",
        "famsize":"GT3",
        "Pstatus":"A",
        "Medu":"4",
        "Fedu":"4",
        "reason":"course",
        "guardian":"mother",
        "traveltime":"2",
        "studytime":"2",
        "failures":"0",
        "schoolsup":"yes",
        "famsup":"no",
        "paid":"no",
        "activities":"no",
        "higher":"yes",
        "internet":"yes",
        "romantic":"no",
        "famrel":"4",
        "freetime":"3",
        "goout":"3",
        "Dalc":"1",
        "Walc":"1",
        "health":"3",
        "absences":"6",
        "G1":"9",
        "G2":"8",
        "G3":"9"
    },
     {
        "id": 8,
        "name":"Spiderman",
        "group": '7J',
        "probdes": 10,
        "sex": "F",
		"age": "18",
        "address": "U",
        "famsize":"GT3",
        "Pstatus":"A",
        "Medu":"4",
        "Fedu":"4",
        "reason":"course",
        "guardian":"mother",
        "traveltime":"2",
        "studytime":"2",
        "failures":"0",
        "schoolsup":"yes",
        "famsup":"no",
        "paid":"no",
        "activities":"no",
        "higher":"yes",
        "internet":"yes",
        "romantic":"no",
        "famrel":"4",
        "freetime":"3",
        "goout":"3",
        "Dalc":"1",
        "Walc":"1",
        "health":"3",
        "absences":"6",
        "G1":"9",
        "G2":"10",
        "G3":"8"
    },
     {
        "id": 9,
        "name":"Hombre de Hierro",
        "group": '8A',
        "probdes": 5,
        "sex": "F",
		"age": "18",
        "address": "U",
        "famsize":"GT3",
        "Pstatus":"A",
        "Medu":"4",
        "Fedu":"4",
        "reason":"course",
        "guardian":"mother",
        "traveltime":"2",
        "studytime":"2",
        "failures":"0",
        "schoolsup":"yes",
        "famsup":"no",
        "paid":"no",
        "activities":"no",
        "higher":"yes",
        "internet":"yes",
        "romantic":"no",
        "famrel":"4",
        "freetime":"3",
        "goout":"3",
        "Dalc":"1",
        "Walc":"1",
        "health":"3",
        "absences":"6",
        "G1":"9",
        "G2":"10",
        "G3":"8"
    },
     {
        "id": 10,
        "name":"Capitan America",
        "group": '5J',
        "probdes": 90,
        "sex": "F",
		"age": "18",
        "address": "U",
        "famsize":"GT3",
        "Pstatus":"A",
        "Medu":"4",
        "Fedu":"4",
        "reason":"course",
        "guardian":"mother",
        "traveltime":"2",
        "studytime":"2",
        "failures":"0",
        "schoolsup":"yes",
        "famsup":"no",
        "paid":"no",
        "activities":"no",
        "higher":"yes",
        "internet":"yes",
        "romantic":"no",
        "famrel":"4",
        "freetime":"3",
        "goout":"3",
        "Dalc":"1",
        "Walc":"1",
        "health":"3",
        "absences":"6",
        "G1":"8",
        "G2":"7",
        "G3":"6"
    }
]

export default studentData;


 